ElectricShop/ElectricShop/Models/DanhSachSanPhamTimKiem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectricShop.Models
{
    public class DanhSachSanPhamTimKiem
    {
        public List<SanPham> dssanphamtimkiem;
        public List<NhaSanXuat> dsnhasanxuat;
        public string tukhoa;
    }
}
        

ElectricShop/ElectricShop/Models/SanPham.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ElectricShop.Models
{
    public class SanPham
    {
        // Thong tin chung
        [Key]
        public int ID { get; set; }
        [DisplayName("Tên sản phẩm có dấu *")]
        [Required(ErrorMessage = "Bạn chưa nhập tên sản phẩm có dấu !")]
        public string TenSPCoDau { get; set; }
        [DisplayName("Tên sản phẩm không dấu *")]
        [Required(ErrorMessage = "Bạn chưa nhập tên sản phẩm có không dấu !")]
        public string TenSPKhongDau { get; set; }
        [DisplayName("Giá gốc *")]
        [Range(0, int.MaxValue, ErrorMessage = "Giá gốc sản phẩm không hợp lệ")]
        [Required(ErrorMessage = "Bạn chưa nhập giá gốc sản phẩm !")]
        [DisplayFormat(DataFormatString = "{0:0,0}")]
        public int GiaGoc { get; set; }
        [DisplayName("Giá khuyến mãi *")]
        [DisplayFormat(DataFormatString = "{0:0,0}")]
        public int GiaGiam { get; set; }
        [DisplayName("Giá Bán")]
        [DisplayFormat(DataFormatString = "{0:0,0}")]
        public int GiaBan { get; set; }
        [DisplayName("Hình đại diện* ")]
        [Required(ErrorMessage = "Bạn chưa chọn ảnh đại diện cho sản phẩm !")]
        public string HinhAnh { get; set;}
        [DisplayName("Loại sản phẩm *")]
        public int LoaiSanPham { get; set; }
        [DisplayName("Màu sắc")]
        public string MauSac { get; set; }
        [DisplayName("Nhà sản xuất")]
        public int NhaSanXuat { get; set; }
        [DisplayName("Xuất xứ")]
        public string XuatXu { get; set; }
        [DisplayName("Bảo hành (tháng)")]
        public int BaoHanh { get; set; }
        [DataType(DataType.Date)]
        public DateTime NgayTao { get; set; }
        [DisplayName("Hiển thị trang chủ")]
        public bool HienThi { get; set; }
        [DisplayName("Sản phẩm bán chạy")]
        public bool SanPhamBanChay { get; set; }
        [DisplayName("Số lượng tồn")]
        public int SoLuong { get; set; }
        [DisplayName("Kích thước thùng")]
        public string KichThuocThung { get; set; }
        [DisplayName("Khối lượng thùng")]
        public string KhoiLuongThung { get; set; }
        [DisplayName("Mô tả chi tiết về sản phẩm")]
        public string MoTa { get; set; }
        // TIVI
        [DisplayName("Kích thước màn hình")]
        public string KichThuocMH { get; set; }
        [DisplayName("Độ phân giải")]
        public string DoPhanGiai { get; set; }
        [DisplayName("màn hình cong")]
        public string ManHinhCong { get; set; }
        [DisplayName("Bộ xử lý")]
        public string BoXuLy { get; set; }
        [DisplayName("SmartTV")]
        public string SmartTV { get; set; }
        [DisplayName("Tần số web")]
        public string TanSoQuet { get; set; }
        [DisplayName("Công suất loa")]
        public string CongSuatLoa { get; set; }
        [DisplayName("Cổng Wifi")]
        public string CongWiFi { get; set; }
        [DisplayName("Cổng Internet")]
        public string CongInternet { get; set; }
        [DisplayName("Cổng HDMI")]
        public string CongHDMI { get; set; }
        [DisplayName("Cổng USB")]
        public string CongUSB { get; set; }
        [DisplayName("Chia sẻ thông ming")]
        public string ChiaSeThongMinh { get; set; }
        [DisplayName("Hệ điều hành")]
        public string HeDeHanh { get; set; }
        [DisplayName("Trình duyệt web")]
        public string TrinhDuyetWeb { get; set; }
        // Dan may nghe nhac
        [DisplayName("Loại dàn máy")]
        public string LoaiDanMay { get; set; }
        [DisplayName("Loại đầu đĩa")]
        public string LoaiDauDia { get; set; }
        
    }
}

ElectricShop/ElectricShop/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ElectricShop.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Net.Http.Headers;
using System.IO;

namespace ElectricShop.Controllers
{
    public class SanPhamController : Controller
    {
        private readonly ElectricShopContext _context;
        private IHostingEnvironment hostingEnv;

        public SanPhamController(ElectricShopContext context, IHostingEnvironment env)
        {
            _context = context;
            this.hostingEnv = env;
        }
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Tao([Bind("ID,HoTen,Email,SoDienThoai,NoiDung")] BinhLuan binhLuan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(binhLuan);
                await _context.SaveChangesAsync();
                return RedirectToAction("TrangChu","TrangChu");
            }
            return View("ChiTiet",binhLuan);
        }


        public async Task<IActionResult> ChiTietSanPham(string id)
        {
            var sanpham = await _context.SanPham
                .SingleOrDefaultAsync(m => m.TenSPKhongDau == id);
            var dsloaisanpham = from lsp in _context.LoaiSanPham
                                select lsp;
            ViewData["menu"] = dsloaisanpham;
            var nhasanxuat = await _context.NhaSanXuat
               .SingleOrDefaultAsync(m => m.ID == sanpham.NhaSanXuat);
            string HangSanXuat = nhasanxuat.TenNSXCoDau;
            var dssanphamlienquan = (from splq in _context.SanPham
                                     where splq.LoaiSanPham == sanpham.LoaiSanPham && splq.TenSPKhongDau != id
                                     select splq).Take(4);
            var dsbinhluan = from bl in _context.BinhLuan
                             where bl.MaSanPham == sanpham.ID
                             orderby bl.ThoiGian descending
                             select bl;

            var chitietsanpham = new DuLieuChiTietSanPham();
            chitietsanpham.dssanphamlienquan = await dssanphamlienquan.ToListAsync();
            chitietsanpham.sanpham = sanpham;
            chitietsanpham.HangSanXuat = HangSanXuat;
            chitietsanpham.dsbinhluan = await dsbinhluan.ToListAsync();
            return View(chitietsanpham);
        }

        public async Task<IActionResult> ChiTiet(string id)
        {
            var sanpham = await _context.SanPham
                .SingleOrDefaultAsync(m => m.TenSPKhongDau== id);
            var dsloaisanpham = from lsp in _context.LoaiSanPham
                                select lsp;
            ViewData["menu"] = dsloaisanpham;
            var nhasanxuat = await _context.NhaSanXuat
               .SingleOrDefaultAsync(m => m.ID == sanpham.NhaSanXuat);
            string HangSanXuat = nhasanxuat.TenNSXCoDau;
            var dssanphamlienquan = (from splq in _context.SanPham
                                     where splq.LoaiSanPham==sanpham.LoaiSanPham && splq.TenSPKhongDau!=id 
                                     select splq).Take(6);
            var dsbinhluan = from bl in _context.BinhLuan
                             where bl.MaSanPham == sanpham.ID
                             orderby bl.ThoiGian descending
                             select bl;

            var chitietsanpham = new DuLieuChiTietSanPham();
            chitietsanpham.dssanphamlienquan = await dssanphamlienquan.ToListAsync();
            chitietsanpham.sanpham = sanpham;
            chitietsanpham.HangSanXuat = HangSanXuat;
            chitietsanpham.dsbinhluan = await dsbinhluan.ToListAsync();
            return View(chitietsanpham);
        }
        //Ajax thêm bình luận
        public async Task<ActionResult> BinhLuan(BinhLuan binhLuan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(binhLuan);
                await _context.SaveChangesAsync();
                string s = "<p><span style='font-size:17px;'><b>" + binhLuan.HoTen+" : </b></span>"+binhLuan.NoiDung+ "</p> <p><a href='#'>Thích </a> &emsp; <a href='#'> Trả lời </a>&emsp;"+   binhLuan.ThoiGian+"</p><hr/>";
                return Content(s, "text/plain");
            }
            return View("ChiTiet", binhLuan);
        }

        public async Task<ActionResult> BinhLuan1(BinhLuan binhLuan)
        {
            if (ModelState.IsValid)
            {
                var ngayht = DateTime.Now.ToLocalTime();
                binhLuan.ThoiGian = ngayht;
                _context.Add(binhLuan);
                await _context.SaveChangesAsync();


                string rs="<div class='review-item clearfix'>"+
                                "<div class='review-item-submitted'>"+
                                    "<strong>"+binhLuan.HoTen+"</strong>"+
                                    "<em>"+ngayht+"</em>"+
                                "</div>"+
                                "<div class='review-item-content'>"+
                                    "<p> "+binhLuan.NoiDung+"</p>"+
                                "</div>"+
                            "</div>";


                return Content(rs, "text/plain");
            }
            return View("ChiTiet", binhLuan);
        }



        public async Task<IActionResult> DanhSachSanPhamTheoLoai1(string id, string hang, string gia)
        {
            // Loại sản phẩm tương ứng
            var loaisanpham = await _context.LoaiSanPham
                .SingleOrDefaultAsync(m => m.TenLoaiSPKhongDau == id);
            //Danh sách sản phẩm ứng với loại trên
            var dssanpham = from sp in _context.SanPham
                            where sp.LoaiSanPham == loaisanpham.ID
                            select sp;
            //Lấy các nhà sản xuất tương ứng của loại sản phẩm này hiện co ở cửa hàng
            var dsnsx = from key in dssanpham
                        group key by key.NhaSanXuat;
            var dsnhasanxuat = from nsx in _context.NhaSanXuat
                               join k in dsnsx on nsx.ID equals k.Key
                               select nsx;
            // Lọc sản phẩm theo hãng sãn xuất
            ViewData["hang"] = "";
            if (!String.IsNullOrEmpty(hang))
            {
                var nhasanxuat = await _context.NhaSanXuat
                    .SingleOrDefaultAsync(m => m.TenNSXKhongDau == hang);
                dssanpham = dssanpham.Where(h => h.NhaSanXuat.Equals(nhasanxuat.ID));
                ViewData["hang"] = hang;
            }

            //Lọc sản phẩm theo giá
            ViewData["gia"] = "";
            if (!String.IsNullOrEmpty(gia))
            {
                if (gia.Equals("duoi-5-trieu"))
                {
                    dssanpham = dssanpham.Where(g => g.GiaBan < 5000000);
                    ViewData["gia"] = "duoi-5-trieu";
                }
                else
                {
                    if (gia.Equals("tu-5-7-trieu"))
                    {
                        dssanpham = dssanpham.Where(g => (g.GiaBan >= 5000000 && g.GiaBan < 7000000));
                        ViewData["gia"] = "tu-5-7-trieu";
                    }
                    else
                    {
                        if (gia.Equals("tu-7-10-trieu"))
                        {
                            dssanpham = dssanpham.Where(g => (g.GiaBan >= 7000000 && g.GiaBan < 10000000));
                            ViewData["gia"] = "tu-7-10-trieu";
                        }
                        else
                        {
                            dssanpham = dssanpham.Where(g => g.GiaBan > 10000000);
                            ViewData["gia"] = "tren-10-trieu";
                        }
                    }
                }
            }

            //Dữ liệu truyền sang View
            var dssanphamtheoloai = new DuLieuDanhSachSanPhamTheoLoai();
            dssanphamtheoloai.dssanphamtheoloai = await dssanpham.ToListAsync();
            dssanphamtheoloai.loaisanpham = loaisanpham;
            dssanphamtheoloai.dsnhasanxuat = await dsnhasanxuat.ToListAsync();
            return View(dssanphamtheoloai);
        }


        public async Task<IActionResult> DanhSachSanPhamKhuyenMai1(string loai,string hang, string gia)
        {
            var dsSanPhamKhuyenMai = from sp in _context.SanPham
                                     where sp.GiaGiam > 0
                                     select sp;

            var dsIDLoaiSanPhamKhuyenMai = from lsp in dsSanPhamKhuyenMai
                                         group lsp by lsp.LoaiSanPham;
            var dsLoaiSanPhamKhuyenMai = from lsp in _context.LoaiSanPham
                                         join k in dsIDLoaiSanPhamKhuyenMai on lsp.ID equals k.Key
                                         select lsp;
            //Lấy các nhà sản xuất tương ứng của loại sản phẩm này hiện co ở cửa hàng
            var dsnsx = from key in dsSanPhamKhuyenMai
                        group key by key.NhaSanXuat;
            var dsnhasanxuat = from nsx in _context.NhaSanXuat
                               join k in dsnsx on nsx.ID equals k.Key
                               select nsx;
            //Lọc theo loại sản phẩm
            ViewData["loai"] = "";
            if (!String.IsNullOrEmpty(loai))
            {
                var loaisanpham = await _context.LoaiSanPham
                    .SingleOrDefaultAsync(m => m.TenLoaiSPKhongDau == loai);
                dsSanPhamKhuyenMai = dsSanPhamKhuyenMai.Where(h => h.LoaiSanPham.Equals(loaisanpham.ID));
                ViewData["loai"] = loai;
            }
            // Lọc sản phẩm theo hãng sãn xuất
            ViewData["hang"] = "";
            if (!String.IsNullOrEmpty(hang))
            {

ElectricShop/ElectricShop/Views/SanPham/DanhSachSanPhamKhuyenMai.cshtml
@model IEnumerable<ElectricShop.Models.LoaiSanPham>
@{
    ViewData["Title"] = "Sản phẩm";
    Layout = "~/Views/Shared/_ClientLayout1.cshtml";
}

<div class="row margin-bottom-40 ">
    <div class="sidebar col-md-3 col-sm-4">
        @await Component.InvokeAsync("Siderbar_SPBCComponent")
    </div>
    <!--Danh sach sản phẩm-->
    <div class="col-md-9 col-sm-8">
        @foreach (var lsp in Model)
        {
            <div style="text-align:center; font-weight:bold;background-color:#66FFCC;font-size:20px; padding-top:5px;padding-bottom:5px;">@lsp.TenLoaiSPCoDau @lsp.ID</div><br />
            @await Component.InvokeAsync("DSSanPhamKhuyenMaiComponent", lsp.ID)
        }
    </div>
 </div>
<script>
    var nf = Intl.NumberFormat();
    var x = 42000000;
    alert(nf.format(x));
</script>

ElectricShop/ElectricShop/Views/SanPham/DanhSachSanPhamKhuyenMai1.cshtml
@model ElectricShop.Models.DuLieuDanhSachSanPhamKhuyenMai
@{
    ViewData["Title"] = "Danh sách sản phẩm theo loại";
    Layout = "~/Views/Shared/_ClientLayout1.cshtml";
}
<div class="row margin-bottom-40 ">
    <div class="sidebar col-md-3 col-sm-4">
        @await Component.InvokeAsync("Siderbar_SPBCComponent")
    </div>
    <!--Danh sach sản phẩm-->
    <div class="col-md-9 col-sm-8">

        <form asp-controller="SanPham" asp-action="DanhSachSanPhamKhuyenMai1" method="get">
            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        <div class="form-group">
                            <label>Chọn loại sản phẩm</label>
                            <select class="form-control" name="loai" onchange="this.form.submit();">
                                <option value="">---Tất cả---</option>
                                @foreach (var lsp in Model.dsloaisanpham)
                                {
                                    if (ViewData["loai"].Equals(lsp.TenLoaiSPKhongDau))
                                    {
                                        <option value="@lsp.TenLoaiSPKhongDau" selected="selected">@lsp.TenLoaiSPCoDau</option>
                                    }
                                    else
                                    {
                                        <option value="@lsp.TenLoaiSPKhongDau">@lsp.TenLoaiSPCoDau</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <div class="form-group">
                            <label>Chọn nhà sản xuất</label>
                            <select class="form-control" name="hang" onchange="this.form.submit();">
                                <option value="">---Tất cả---</option>
                                @foreach (var nsx in Model.dsnhasanxuat)
                                {
                                    if (ViewData["hang"].Equals(nsx.TenNSXKhongDau))
                                    {
                                        <option value="@nsx.TenNSXKhongDau" selected="selected">@nsx.TenNSXCoDau</option>
                                    }
                                    else
                                    {
                                        <option value="@nsx.TenNSXKhongDau">@nsx.TenNSXCoDau</option>

                                    }

                                }
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <div class="form-group">
                            <label>Chọn mức giá</label>
                            <select class="form-control" name="gia" onchange="this.form.submit();">
                                <option value="">---Tất cả---</option>
                                @{
                                    if (ViewData["gia"].Equals("duoi-5-trieu"))
                                    {
                                        <option value="duoi-5-trieu" selected="selected">Dưới 5 triệu</option>
                                    }
                                    else
                                    {
                                        <option value="duoi-5-trieu">Dưới 5 triệu</option>
                                    }
                                }
                                @{
                                    if (ViewData["gia"].Equals("tu-5-7-trieu"))
                                    {
                                        <option value="tu-5-7-trieu" selected="selected">Từ 5 đến 7 triệu</option>
                                    }
                                    else
                                    {
                                        <option value="tu-5-7-trieu">Từ 5 đến 7 triệu</option>

                                    }
                                }
                                @{
                                    if (ViewData["gia"].Equals("tu-7-10-trieu"))
                                    {
                                        <option value="tu-7-10-trieu">Từ 5 đến 7 triệu</option>
                                    }
                                    else
                                    {
                                        <option value="tu-7-10-trieu">Từ 5 đến 7 triệu</option>

                                    }
                                }
                                @{
                                    if (ViewData["gia"].Equals("tren-10-trieu"))
                                    {
                                        <option value="tren-10-trieu">Từ 5 đến 7 triệu</option>
                                    }
                                    else
                                    {
                                        <option value="tren-10-trieu">Từ 5 đến 7 triệu</option>

                                    }
                                }
                            </select>
                        </div>
                    </div>
                </div>


            </div>
        </form>
        <h2>Danh sách sản phẩm khuyến mãi</h2>
        <div class="row" style="margin-top:20px;">
            @foreach (var sp in Model.dssanphamkhuyenmai)
            {
                <div class="col-md-3">
                    <div class="product-item">
                        <div class="pi-img-wrapper">
                            <img src="/@sp.HinhAnh" class="img-responsive" alt="Berry Lace Dress">
                            <div>
                                <a href="/@sp.HinhAnh" class="btn btn-default fancybox-button">Zoom</a>
                                <a asp-controller="SanPham" asp-action="ChiTiet" asp-route-id="@sp.TenSPKhongDau" class="btn btn-default fancybox-fast-view">View</a>
                            </div>
                        </div>
                        <h3><a href="shop-item.html">@sp.TenSPCoDau</a></h3>
                        <div class="pi-price">@Html.DisplayFor(modelItem => sp.GiaBan) vnd </div>
                        <div style="clear:both;">
                            @{
                                if (sp.GiaGiam != 0)
                                {
                                    @: <span style="text-decoration:line-through;">@Html.DisplayFor(modelItem => sp.GiaGoc) vnd</span>&nbsp;<span style="background-color:red;">-@(sp.GiaGiam * 100 / sp.GiaGoc) %</span>
                                    <div class="sticker sticker-sale"></div>
                                }
                            }
                            &nbsp;
                        </div>
                        <div style="margin-top:5px;"><a href="https://www.w3schools.com/bootstrap/bootstrap_grid_system.asp" class="btn btn-default add2cart">Add to cart</a></div>

                    </div>
                </div>
                                }
        </div>


    </div>
</div>

ElectricShop/ElectricShop/Views/SanPham/DanhSachSanPhamTheoLoai.cshtml
@model ElectricShop.Models.DuLieuDanhSachSanPhamTheoLoai
@{
    ViewData["Title"] = Model.loaisanpham.TenLoaiSPCoDau;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>@Model.loaisanpham.TenLoaiSPCoDau</h4>
<div>
    <form asp-controller="SanPham" asp-action="DanhSachSanPhamTheoLoai" method="get">
        
        <hr />
        <span style="font-size:18px;">Hãng sản xuất</span>:&emsp;&emsp;
        @foreach (var nsx in Model.dsnhasanxuat)
        {
            if (ViewData["hang"].Equals(nsx.TenNSXKhongDau))
            {
                @: <input type="radio" name="hang" value="@nsx.TenNSXKhongDau" onclick="this.form.submit();" checked="checked" /> @nsx.TenNSXCoDau &emsp;
            }
            else
            {
                @: <input type="radio" name="hang" value="@nsx.TenNSXKhongDau" onclick="this.form.submit();"/> @nsx.TenNSXCoDau &emsp;
            }
           
        }
        <hr />
        <span style="font-size:18px;">Giá bán:</span>&emsp;&emsp;
        @{
            if (ViewData["gia"].Equals("duoi-5-trieu"))
            {
               @:<input name="gia" type="radio" value="duoi-5-trieu" checked="checked" onclick="this.form.submit();" /> Dưới 5 triệu &emsp;
            }
            else
            {
                @:<input name="gia" type="radio" value="duoi-5-trieu" onclick="this.form.submit();"/> Dưới 5 triệu &emsp;
            }
        }
        @{
            if (ViewData["gia"].Equals("tu-5-7-trieu"))
            {
                @:<input name="gia" type="radio" value="tu-5-7-trieu" checked="checked" onclick="this.form.submit();"/> Từ 5 - 7 triệu&emsp;
            }
            else
            {
                @:<input name="gia" type="radio" value="tu-5-7-trieu" onclick="this.form.submit();" /> Từ 5 - 7 triệu&emsp;
            }
        }
        @{
            if (ViewData["gia"].Equals("tu-7-10-trieu"))
            {
                @:<input name="gia" type="radio" value="tu-7-10-trieu" checked="checked" onclick="this.form.submit();" /> Từ 7 - 10 triệu&emsp;
            }
            else
            {
                @:<input name="gia" type="radio" value="tu-7-10-trieu" onclick="this.form.submit();" /> Từ 7 - 10 triệu&emsp;
            }
        }
        @{
            if (ViewData["gia"].Equals("tren-10-trieu"))
            {
                @:<input name="gia" type="radio" value="ttren-10-trieu" checked="checked" onclick="this.form.submit();"/> Trên 10 triệu&emsp;
            }
            else
            {
                @:<input name="gia" type="radio" value="tren-10-trieu" onclick="this.form.submit();"/> Trên 10 triệu&emsp;
            }
        }
    </form>
</div>
<hr />
<ul class="thumbnails">
    @foreach (var spht in Model.dssanphamtheoloai)
    {
        <li class="span3">
            <div class="thumbnail">
                <a asp-controller="SanPham" asp-action="ChiTiet" asp-route-id="@spht.TenSPKhongDau"><img src="~/@spht.HinhAnh" alt="" /></a>
                <div class="caption">
                    <h5 style="color:blue;text-align:center;">@spht.TenSPCoDau</h5>
                    <p>
                        <h4 style="color:red;text-align:center;">@Html.DisplayFor(modelItem => spht.GiaGiam) vnđ</h4>
                    </p>
                    <p>
                        @{
                            if (!(spht.Gia == spht.GiaGiam))
                            {
                                <h5> <span style="text-decoration:line-through" class="giagoc"> @Html.DisplayFor(modelItem => spht.Gia) vnđ  </span> &nbsp;<span style="background-color:red;color:white;">-@(100 - spht.GiaGiam * 100 / spht.Gia)%</span></h5>
                            }
                        }
                    </p>

                    <h4 style="text-align:center"><a class="btn" asp-controller="SanPham" asp-action="ChiTiet" asp-route-id="@spht.TenSPKhongDau"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a> </h4>
                </div>
            </div>
        </li>


                            }
</ul>

ElectricShop/ElectricShop/Views/SanPham/DanhSachSanPhamTimKiem.cshtml
@model ElectricShop.Models.DanhSachSanPhamTimKiem
@{
    ViewData["Title"] = "Ket qua tim kiem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Các sản phẩm tìm kiếm cho từ khoa " @Model.tukhoa " </h4>

<ul class="thumbnails">
    @foreach (var spht in Model.dssanphamtimkiem)
    {
        @*<li class="span3">
                <div class="thumbnail">
                    <a asp-controller="SanPham" asp-action="ChiTiet" asp-route-id="@spht.TenSPKhongDau"><img src="~/@spht.HinhAnh" alt="" /></a>
                    <div class="caption">
                        <h5 style="color:red;text-align:center;">@spht.TenSPCoDau</h5>
                        <p>
                            <h5>@spht.Gia đồng</h5>
                        </p>

                        <h4 style="text-align:center"><a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a> </h4>
                    </div>
                </div>
            </li>*@


        <li class="span3">
            <div class="thumbnail">
                <a asp-controller="SanPham" asp-action="ChiTiet" asp-route-id="@spht.TenSPKhongDau"><img src="~/@spht.HinhAnh" alt="" /></a>
                <div class="caption">
                    <h5 style="color:blue;text-align:center;">@spht.TenSPCoDau</h5>
                    <p>
                        <h4 style="color:red;text-align:center;">@Html.DisplayFor(modelItem => spht.GiaGiam) vnđ</h4>
                    </p>
                    <p>
                        @{
                            if (!(spht.Gia == spht.GiaGiam))
                            {
                                <h5> <span style="text-decoration:line-through;" class="giagoc"> @Html.DisplayFor(modelItem => spht.Gia) vnđ  </span> &nbsp;<span style="background-color:red;color:white;">-@(100 - spht.GiaGiam * 100 / spht.Gia)%</span></h5>
                            }
                        }
                    </p>

                    <h4 style="text-align:center"><a class="btn" asp-controller="SanPham" asp-action="ChiTiet" asp-route-id="@spht.TenSPKhongDau"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a> </h4>
                </div>
            </div>
        </li>
     }
</ul>

ElectricShop/ElectricShop/Views/SanPham/a.cshtml
aaaaaaaaaaa