ElectricShop/ElectricShop/Models/SanPhamBan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ElectricShop.Models
{
    public class SanPhamBan
    {
        public int ID { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Bạn chưa chọn sản phẩm")]
        [Required(ErrorMessage = "bạn chưa chọn sản phẩm !")]
        public int sanPhamID { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Bạn chưa nhập đầy đủ thông tin khách hàng")]
        public int khachHangID { get; set; }
        [Required(ErrorMessage = "bạn chưa nhập mã bảo hành !")]
        public string maBaoHanh { get; set; }
        public DateTime ngayBan { get; set; }
    }
}

ElectricShop/ElectricShop/Controllers/SanPhamBanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ElectricShop.Models;

namespace ElectricShop.Controllers
{
    public class SanPhamBanController : Controller
    {
        private readonly ElectricShopContext _context;

        public SanPhamBanController(ElectricShopContext context)
        {
            _context = context;    
        }
        public async Task<IActionResult> BanHang()
        {
            var dsLoaiSanPham = from lsp in _context.LoaiSanPham
                                select lsp;
            var loaiSanPhamDauTien = await (from lsp in dsLoaiSanPham
                                       select lsp).FirstOrDefaultAsync();
            var dsSanPhamTheoLoai = from sp in _context.SanPham
                                    where sp.LoaiSanPham == loaiSanPhamDauTien.ID
                                    select sp;
            ViewBag.dsLoaiSanPham =await dsLoaiSanPham.ToListAsync();
            ViewBag.dsSanPhamTheoLoai = await dsSanPhamTheoLoai.ToListAsync();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BanHang([Bind("ID,sanPhamID,khachHangID,maBaoHanh")] SanPhamBan SanPhamBan,string TenSP)
        {
            if (ModelState.IsValid)
            {
                var ngayTao = DateTime.Now;
                SanPhamBan.ngayBan = ngayTao;
                _context.Add(SanPhamBan);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            var khachhang = (from kh in _context.KhachHang
                            where kh.ID == SanPhamBan.khachHangID
                            select kh).FirstOrDefault();
            if(khachhang!=null)
            {
                ViewBag.tenKH = khachhang.HoTenKhachHang;
                ViewBag.soDT = khachhang.SoDienThoai;
                ViewBag.diaChi = khachhang.DiaChi;
            }
            ViewBag.tenSP = TenSP;
            ViewBag.sanPhamID = SanPhamBan.sanPhamID;
            var dsLoaiSanPham = from lsp in _context.LoaiSanPham
                                select lsp; 
            var loaiSanPhamDauTien = await (from lsp in dsLoaiSanPham
                                            select lsp).FirstOrDefaultAsync();
            var dsSanPhamTheoLoai = from sp in _context.SanPham
                                    where sp.LoaiSanPham == loaiSanPhamDauTien.ID
                                    select sp;
            ViewBag.dsLoaiSanPham = await dsLoaiSanPham.ToListAsync();
            ViewBag.dsSanPhamTheoLoai = await dsSanPhamTheoLoai.ToListAsync();
            return View(SanPhamBan);
        }
        //Ajax load danh sách sản phẩm theo loại
        public IActionResult LoadSanPhamTheoLoai(int idlsp)
        {
            var dsSanPhamTheoLoai = from sp in _context.SanPham
                                    where sp.LoaiSanPham == idlsp
                                    select sp;
            var rs = "";
            foreach(var sp in dsSanPhamTheoLoai)
            {
                rs = rs + "<option value= '"+sp.ID+"'>"+ sp.TenSPCoDau+ "</option>";
            }
            return Content(rs);
        }

        //Ajax load danh sách sản phẩm theo loại
        public IActionResult LoadThongTinSanPham(int idsp)
        {
            var sanPham = (from sp in _context.SanPham
                          where sp.ID == idsp
                          select sp).FirstOrDefault();
            var rs = "<div class='col-sm-5'>"+
                    "<img src='"+sanPham.HinhAnh+ "' class='img-rounded'  width='150' height='150'>"+
            "</div>"+
            "<div class='col-sm-7'>"+
                "<p id='tensp'><b>"+sanPham.TenSPCoDau+"</b></p>"+
                "<p>Giá gốc :"+sanPham.GiaGoc+"</p>"+
                "<p>Giá giảm :" + sanPham.GiaGiam + "</p>" +
            "</div>" +
            "<input type='hidden' id ='masp' value='" + sanPham.ID + "' />";

            return Content(rs);
        }

        //Ajax load danh sách sản phẩm theo loại
        public IActionResult LoadThongTinSanPhamDauTien(int idlsp)
        {
            var dsSanPhamTheoLoai = (from sp in _context.SanPham
                                    where sp.LoaiSanPham == idlsp
                                    select sp).FirstOrDefault();
            var sanPham = (from sp in _context.SanPham
                           where sp.ID == dsSanPhamTheoLoai.ID
                           select sp).FirstOrDefault();
            var rs = "<div class='col-sm-5'>" +
                    "<img src='" + sanPham.HinhAnh + "' class='img-rounded'  width='150' height='150'>" +
            "</div>" +
            "<div class='col-sm-7'>" +
                "<p id='tensp'><b>" + sanPham.TenSPCoDau + "</b></p>" +
                "<p>Giá gốc :" + sanPham.GiaGoc + "</p>" +
                "<p>Giá giảm :" + sanPham.GiaGiam + "</p>" +
            "</div>"+
            "<input type='hidden' id ='masp' value='"+sanPham.ID+"' />";
            return Content(rs);
        }

        // GET: SanPhamBan
        public async Task<IActionResult> Index()
        {
            return View(await _context.SanPhamBan.ToListAsync());
        }

        // GET: SanPhamBan/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var SanPhamBan = await _context.SanPhamBan
                .SingleOrDefaultAsync(m => m.ID == id);
            if (SanPhamBan == null)
            {
                return NotFound();
            }

            return View(SanPhamBan);
        }

        // GET: SanPhamBan/Create
        public IActionResult Create()
        {
            var dssp = from spb in _context.SanPhamBan
                       select spb;
            ViewBag.dsLoaiSanPham = dssp.ToList();
            return View();
        }
        // POST: SanPhamBan/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,sanPhamID,khachHangID,maBaoHanh")] SanPhamBan SanPhamBan)
        {
            var dssp = from spb in _context.SanPhamBan
                       select spb;
            ViewBag.dsLoaiSanPham = dssp.ToList();
            if (ModelState.IsValid)
            {
                _context.Add(SanPhamBan);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(SanPhamBan);
        }

        // GET: SanPhamBan/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var SanPhamBan = await _context.SanPhamBan.SingleOrDefaultAsync(m => m.ID == id);
            if (SanPhamBan == null)
            {
                return NotFound();
            }
            return View(SanPhamBan);
        }

        // POST: SanPhamBan/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,sanPhamID,maBaoHanh,ngayBan")] SanPhamBan SanPhamBan)
        {
            if (id != SanPhamBan.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(SanPhamBan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamBanExists(SanPhamBan.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(SanPhamBan);
        }

        // GET: SanPhamBan/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var SanPhamBan = await _context.SanPhamBan
                .SingleOrDefaultAsync(m => m.ID == id);
            if (SanPhamBan == null)
            {
                return NotFound();
            }

            return View(SanPhamBan);
        }

        // POST: SanPhamBan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var SanPhamBan = await _context.SanPhamBan.SingleOrDefaultAsync(m => m.ID == id);
            _context.SanPhamBan.Remove(SanPhamBan);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool SanPhamBanExists(int id)
        {
            return _context.SanPhamBan.Any(e => e.ID == id);
        }
    }
}

ElectricShop/ElectricShop/Views/SanPhamBan/BanHang.cshtml
@model ElectricShop.Models.SanPhamBan
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var dsLoaiSanPham = (List<ElectricShop.Models.LoaiSanPham>)ViewBag.dsLoaiSanPham;
    var dsSanPham = (List<ElectricShop.Models.SanPham>)ViewBag.dsSanPhamTheoLoai;
    var sanphamID = ViewBag.sanPhamID;
    sanphamID = Convert.ToString(sanphamID);
    if (String.IsNullOrEmpty(sanphamID)) { sanphamID ="0"; }
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#loaisanpham').change(function () {
            $.ajax({
                url: '/SanPhamBan/LoadSanPhamTheoLoai',
                type: 'POST',
                data: { "idlsp": $('#loaisanpham').val() },
                success: function (rs) {
                    $('#slsanpham').html(rs);
                }
            });

            $.ajax({
                url: '/SanPhamBan/LoadThongTinSanPhamDauTien',
                type: 'POST',
                data: { "idlsp": $('#loaisanpham').val() },
                success: function (rs) {
                    $('#thongtinsanpham').html(rs);
                }
            });
        });

        $('#slsanpham').change(function () {
            $.ajax({
                url: '/SanPhamBan/LoadThongTinSanPham',
                type: 'POST',
                data: { "idsp": $('#slsanpham').val() },
                success: function (rs) {
                    $('#thongtinsanpham').html(rs);
                }
            });
        });

        $('#chonsanpham').click(function () {
            $('#tensanpham').val($('#tensp').text());
            $('#masanpham').val($('#masp').val());
        });
        $('#tao').click(function () {
            $.ajax({
                url: '/KhachHang/ThemKhachHang',
                type: 'POST',
                data: $('#form_kh').serialize(),
                success: function (rs)
                {
                    $('#makhachhang').val(rs);
                    $('#form_banhang').submit();
                },
                error : function ()
                {
                    $('#makhachhang').val("");
                }
            });
        });
        
    });
</script>
@{ 
    var location = new Uri($"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}");

    var url = location.AbsoluteUri;
}
<h2>Bán hàng</h2>
<h1>@($"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}")</h1>
<h1>@url</h1>
<div class="row">
    <div class="col-sm-5">
        
        <form class="form-horizontal">
            <div class="form-group">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <label class="control-label col-sm-4">Loại sản phẩm</label>
                <div class="col-sm-7">
                    <select class="form-control" id="loaisanpham" >
                        <option>---Chọn loại sản phẩm---</option>
                        @foreach (var lsp in dsLoaiSanPham)
                        {
                            <option  value="@lsp.ID">@lsp.TenLoaiSPCoDau</option>
                        }
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-4">Sản phẩm</label>
                <div class="col-sm-7">
                    <select class="form-control" id="slsanpham">
                        <option>---Chọn sản phẩm---</option>
                        @foreach (var sp in dsSanPham)
                        {
                            <option value="@sp.ID">@sp.TenSPCoDau</option>
                        }
                    </select>
                </div>
            </div>
        </form>
        <hr />
        <div class="row">
            <div class="col-sm-7">
                <h3>Thông tin sản phẩm</h3>
            </div>
            <div class="col-sm-5">
                <button type="button" class="btn btn-primary btn-sm" id="chonsanpham">Chọn sản phẩm <span class="glyphicon glyphicon-play"></span></button>
            </div>
        </div>
        <div class="row" id="thongtinsanpham">
        </div>
        
    </div>
    <div class="col-sm-7" >

        <form class="form-horizontal"  id="form_kh">
            <div class="form-group">
                <label  class="control-label col-sm-3">Họ tên khách hàng *</label>
                <div class="col-sm-7">
                    <input type="text" name="HoTenKhachHang" value="@ViewBag.tenKH" class="form-control" placeholder="Nhập tên sản phẩm có dấu">
                    <span  class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label  class="control-label col-sm-3" >Số điện thoại *</label>
                <div class="col-sm-7">
                    <input type="text"  class="form-control" value="@ViewBag.soDT"  placeholder="Nhập tên sản phẩm không dấu" name="SoDienThoai">
                    <span  class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-3" >Địa chỉ</label>
                <div class="col-sm-7">
                    <input type="text" class="form-control" value="@ViewBag.diaChi"  placeholder="Nhập tên sản phẩm không dấu" name="DiaChi">
                    <span class="text-danger"></span>
                </div>
            </div>
        </form>

        <form class="form-horizontal" id="form_banhang" asp-controller="SanPhamBan" asp-action="BanHang">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label col-sm-3">Tên sản phẩm</label>
                <div class="col-sm-7">
                    <input type="text" class="form-control" value="@ViewBag.tenSP" name="TenSP" id="tensanpham"  placeholder="Nhập tên sản phẩm không dấu">
                </div>
            </div>
            <input type="hidden" value="@sanphamID" id="masanpham"  asp-for="sanPhamID" />
            <input type="hidden" asp-for="khachHangID" id="makhachhang" />
            <div class="form-group">
                <label class="control-label col-sm-3">Mã bảo hành</label>
                <div class="col-sm-7">
                    <input type="text" asp-for="maBaoHanh" class="form-control" placeholder="Nhập tên sản phẩm không dấu">
                    <span asp-validation-for="maBaoHanh" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-3 col-md-10">
                    <span asp-validation-for="sanPhamID" class="text-danger"></span><br />
                    <span asp-validation-for="khachHangID" class="text-danger"></span>
                </div>
                
            </div>
            
        </form>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-7">
                <input type="button" id="tao" value="Tạo" class="btn btn-default" />
            </div>
        </div>
    </div>
</div>

ElectricShop/ElectricShop/Views/SanPhamBan/Create.cshtml
@model ElectricShop.Models.SanPhamBan

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>SanPhamDaBan</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="sanPhamID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="sanPhamID" class="form-control" />
                <span asp-validation-for="sanPhamID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group" >
            <label asp-for="maBaoHanh" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="maBaoHanh" class="form-control" />
                <span asp-validation-for="maBaoHanh" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="khachHangID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="khachHangID" class="form-control" />
                <span asp-validation-for="khachHangID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ngayBan" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ngayBan" class="form-control" />
                <span asp-validation-for="ngayBan" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ElectricShop/ElectricShop/Views/SanPhamBan/Delete.cshtml
@model ElectricShop.Models.SanPhamDaBan

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SanPhamDaBan</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.sanPhamID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.sanPhamID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.maBaoHanh)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.maBaoHanh)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ngayBan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ngayBan)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

ElectricShop/ElectricShop/Views/SanPhamBan/Details.cshtml
@model ElectricShop.Models.SanPhamDaBan

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SanPhamDaBan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sanPhamID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.sanPhamID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.maBaoHanh)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.maBaoHanh)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ngayBan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ngayBan)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ElectricShop/ElectricShop/Views/SanPhamBan/Edit.cshtml
@model ElectricShop.Models.SanPhamDaBan

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>SanPhamDaBan</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="sanPhamID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="sanPhamID" class="form-control" />
                <span asp-validation-for="sanPhamID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="maBaoHanh" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="maBaoHanh" class="form-control" />
                <span asp-validation-for="maBaoHanh" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ngayBan" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ngayBan" class="form-control" />
                <span asp-validation-for="ngayBan" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ElectricShop/ElectricShop/Views/SanPhamBan/Index.cshtml
@model IEnumerable<ElectricShop.Models.SanPhamBan>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.sanPhamID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.maBaoHanh)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.khachHangID)
            </th>
                <th>
                    @Html.DisplayNameFor(model => model.ngayBan)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.sanPhamID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.maBaoHanh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.khachHangID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ngayBan)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>